language: go
go:
- '1.13'
services:
- docker
cache:
  directories:
  - "$GOPATH/pkg"
before_install:
- go get github.com/mattn/goveralls
install:
- make ci/install
script:
- make ci/test
after_success:
- goveralls -coverprofile=coverage.out -service=travis-ci
