language: go
go:
- '1.13'
services:
- docker
cache:
  directories:
  - "$GOPATH/pkg"
sudo: true
install:
- make setup-ci
script:
- make test-ci
env:
  global:
    secure: hRJ8v4oXnWQlIvu7idYp82/nKvQYDdurtmFHf9OeWkaSvxKs+pU2ZJtNhWxhsLFy7XHhgJLFaWOY56uvWKFj9bgiafQZVaUcjzOXOt5yWuI+qYWvcZIJLgSMCeZS6aydhqpMwmADiUY/Hi0/Tl3vsFyUVodUrTkU6vyxyzFF8TqHcEI6TVnronwzI6S3k/RrxORrX50CY4n7/RK5gJc+tSMxCmQNQOCJUibJg5a4p6Y2v4CFMxHdgs0KfvV0J7/XGUTnaNiFhZ4VJa88S9OqwOpNrgJqtQF8XZQcQpAvB3EIo9OHyrTsXsBWejzxXY27PxwyPsNsM1710+O8bj1P+QS5maPXOfRPM4X8pA7gZo+tMBdhl1APDaNfxttZhGfZ5WJIlrcGBHAa3G6bTZ8G8bp0QMRBJGTpEHSRbCynrbxUyD1ubJugkN6lbPOG7CcZyV6mWDH9cSiBp1+dwihNRanMYrF+dlg8gmq75lWXJih/kfCdR2lCvWBrXR5T/3uRhu8WYk4dT8jvJKLqFx5PLDv5om7oSJ3G2d636jUgQz8E7ktJBzD6s96LEy3i22etfSidXOoDblHBzuwLvR9IpP/AcZejY7irlaYzz+x/5rqj1+bX/KXhCCaa9mYG+YqpAFRcsBbbO+A/f8FQG7EzmKV8F46Zc0IzN+o049fCiVg=
