language: go
go:
- '1.13'
services:
- docker
cache:
  directories:
  - "$GOPATH/pkg"
sudo: true
before_install:
- go get github.com/mattn/goveralls
install:
- make all-ci
script:
- make test-ci
after_success:
- goveralls -coverprofile=coverage.out -service=travis-ci
