language: go

go: '1.13'

jobs:
  include:
    - stage: test
      cache:
        directories:
          - "$GOPATH/pkg"
      services:
      - docker
      before_install:
      - go get github.com/mattn/goveralls
      install:
      - make ci/install
      after_success:
      - goveralls -coverprofile=coverage.out -service=travis-ci
      script:
      - make ci/test
    - stage: deploy
      on:
        tags: true
      services: docker
      script:
      - push_to_docker.sh
