version: '2'
services:
  william:
    image: golang:1.13-alpine
    ports:
      - 4040:4040
    working_dir: /Will.IAM
    volumes:
      - ./:/Will.IAM
    depends_on:
      - oauth2-server
      - postgres
    environment:
      - WILLIAM_EXTENSIONS_PG_HOST=postgres
      - WILLIAM_EXTENSIONS_PG_PORT=5432
    container_name: Will.IAM_app_1
    command: "sh -c 'chmod +x ./wait-for-it.sh && ./wait-for-it.sh postgres oauth2-server:9000 -- go mod download && make run'"
  oauth2-server:
    image: node:14.8
    ports:
      - 9000:9000
    container_name: Will.IAM_oauth2_server_1
    command: bash -c "npm install -g oauth2-mock-server && oauth2-mock-server -p 9000"
  postgres:
    image: postgres:9.6
    ports:
      - "8432:5432"
    volumes:
      - "./docker_data/postgres:/var/lib/postgresql/data"
    container_name: Will.IAM_postgres_1
    command:
      - "postgres"
      - "-c"
      - "max_connections=9999"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
