version: '2'
services:
  oauth2-server:
    image: node:14.8
    ports:
      - 9000:9000
    command: bash -c "npm install -g oauth2-mock-server && oauth2-mock-server -p 9000"
  postgres:
    image: postgres:9.6
    ports:
      - "8432:5432"
    volumes:
      - "./docker_data/postgres:/var/lib/postgresql/data"
    container_name: Will.IAM_postgres_1
    command:
      - "postgres"
      - "-c"
      - "max_connections=9999"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
