verbose: 3
jaeger:
  disabled: false
  samplingProbability: 1
  serviceName: Will.IAM
oauth2:
  provider: dev
  dev:
    authorizationUrl: http://localhost:9000/authorize
    redirectUrl: http://localhost:4040/sso/auth/done
  google:
    clientId: dummy
    clientSecret: dummy
    redirectUrl: dummy
    checkHostedDomain: true
    hostedDomains:
      - domain1
      - domain2
listOptions:
  defaultPageSize: 30
