verbose: 3
jaeger:
  disabled: false
  samplingProbability: 1
  serviceName: Will.IAM
oauth2:
  google:
    clientId: dummy
    clientSecret: dummy
    redirectUrl: dummy
    checkHostedDomain: true
    hostedDomains:
      - domain1
      - domain2
listOptions:
  defaultPageSize: 30
